version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - 5672:5672
      - 15672:15672
  recette_mongodb:    
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./recette/database/mongo:/data/db
      - ./recette/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin
    networks:
      - cloud_computing_network
networks:  
  cloud_computing_network:
